version: "3"
services:
  browser-speech:
    build:
      context: .
      args:
        - "SCENARIO_MANAGER_HOST=http://scenario-engine:5200"
        - "PORT=4100"
    entrypoint:
      - node
      - backend.js
    tty: true
    volumes:
      - "${PWD}:/app"
    ports:
      - "4100:4100"
  scenario-engine:
    build:
      context: .
      dockerfile: scenario-engine/Dockerfile
      args:
        - "BACKEND_HOST=http://browser-speech:4100"
        - "PORT=5200"
    entrypoint:
      - node
      - scenario-engine/index.js
    tty: true
    volumes:
      - "${PWD}:/app"
